### ISSUE TITLE
export SocketFlag

### ISSUE THREAD

**Issue by blaenk** [Ginurx/zmq-rs#2]
The SocketFlag options like [`SNDMORE`](https://github.com/Ginurx/zmq-rs/blob/master/src/socket.rs#L249-L250) are not public, so can't be used with `send_msg`.

**Comment by Ginurx** [comment]
But SocketFlags are defined as below

```
pub type SocketFlag = c_int;

pub const DONTWAIT: SocketFlag = 1;
pub const SNDMORE: SocketFlag = 2;
```

**Comment by blaenk** [comment]
Right, but the `socket` module is not public/re-exported in lib.rs, i.e. it's `mod socket` not `pub mod socket`, so there's no way to do `zmq::socket::SNDMORE`. Unless I'm missing something?

**Comment by Ginurx** [comment]
You're right. Fixed it.
Re-exported items under socket mod with pub use.
You'd use SocketFlag like zmq::DONTWAIT
