### ISSUE TITLE
Are you accepting PRs?

### ISSUE THREAD

**Issue by itpetey** [Ginurx/zmq-rs#3]
This might sound like a stupid question, but I blew some time on this PR: https://github.com/erickt/rust-zmq/pull/84 and it's likely never going to be merged. Are you open to PRs on your repo?

**Comment by Ginurx** [comment]
Sure.  
I can't use rust-zmq on Windows, so I implemented a new one

**Comment by itpetey** [comment]
Cool! :)

I was going to publish my own rust-zmq fork but then I found your lib. Though I didn’t want to port any repos over until I had at least checked that you were planning on maintaining the project.
